### ISSUE TITLE
Shortest path Algorithms

### ISSUE THREAD

**Issue by legion2003** [legion2003/Master-DSA#3]
Make a folder named "Shortest Path Algos" in Graphs folder and add some concepts and algorithm for the same.

**Comment by avezqureshi14** [comment]
Hello Sir, I like to contribute for this , can you please explain the requirement detail that do you want only code

**Comment by codewithnadeem14502** [comment]
hello sir , i would love to do this task , hope you will assign me  this task

**Comment by legion2003** [comment]
> Hello Sir, I like to contribute for this , can you please explain the requirement detail that do you want only code

Yes only code will suffice. Make sure it is clean.

**Comment by naman-ng** [comment]
Sir I think my PR resolved this.
